import { Router } from 'express';
import health from './health';
import users from './users';
import doctorProfiles from './doctorProfiles';
import hospitals from './hospitals';
import jobs from './jobs';
import jobApplications from './jobApplications';
import courses from './courses';
import courseModules from './courseModules';
import courseProgress from './courseProgress';
import courseCertificates from './courseCertificates';
import enrollments from './enrollments';
import moduleTests from './moduleTests';
import testQuestions from './testQuestions';
import testResponses from './testResponses';
import certificates from './certificates';
import masterclasses from './masterclasses';
import masterclassBookings from './masterclassBookings';
import quizzesRoutes from '../modules/quizzes/routes';
import npaAutomationRoutes from '../modules/npa-automation/routes';
import researchRoutes from '../modules/research/routes';
import authRoutes from '../modules/auth/routes';
import aiTools from './aiTools';
import npaOptIns from './npaOptIns';
import npaTemplates from './npaTemplates';
import medicalVoices from './medicalVoices';
import medicalVoiceContacts from './medicalVoiceContacts';
import medicalVoiceUpdates from './medicalVoiceUpdates';
import medicalVoiceSupporters from './medicalVoiceSupporters';
import medicalVoiceGatherings from './medicalVoiceGatherings';
import messages from './messages';
import entityTemplates from './entityTemplates';
import settings from './settings';
import auth from './auth';

const api = Router();

api.use('/health', health);
api.use('/users', users);
api.use('/doctor-profiles', doctorProfiles);
api.use('/hospitals', hospitals);
api.use('/jobs', jobs);
api.use('/job-applications', jobApplications);
api.use('/courses', courses);
api.use('/course-modules', courseModules);
api.use('/course-progress', courseProgress);
api.use('/course-certificates', courseCertificates);
api.use('/enrollments', enrollments);
api.use('/module-tests', moduleTests);
api.use('/test-questions', testQuestions);
api.use('/test-responses', testResponses);
api.use('/certificates', certificates);
api.use('/masterclasses', masterclasses);
api.use('/masterclass-bookings', masterclassBookings);
api.use('/quizzes', quizzesRoutes);
api.use('/npa-automation', npaAutomationRoutes);
api.use('/research', researchRoutes);
api.use('/ai-tools', aiTools);
api.use('/npa-opt-ins', npaOptIns);
api.use('/npa-templates', npaTemplates);
api.use('/medical-voices', medicalVoices);
api.use('/medical-voice-contacts', medicalVoiceContacts);
api.use('/medical-voice-updates', medicalVoiceUpdates);
api.use('/medical-voice-supporters', medicalVoiceSupporters);
api.use('/medical-voice-gatherings', medicalVoiceGatherings);
api.use('/messages', messages);
api.use('/entity-templates', entityTemplates);
api.use('/settings', settings);
api.use('/auth', authRoutes);

export default api;
