name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (CI)
        run: npm ci --ignore-scripts

      - name: Typecheck
        run: npm run check

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          BIGTOS_KEY: ${{ secrets.BIGTOS_KEY }}
          LOG_LEVEL: warn
        run: npm test -- --runInBand --detectOpenHandles
